spring.application.name=library-management-system

spring.datasource.url = jdbc:postgresql://your-db-url
spring.datasource.password=your-pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.propertiesoperties.hibernate.default_batch_fetch_size=50

server.servlet.context-path=/api

spring.jpa.show-sql=true
