spring.application.name=library-management-system

spring.datasource.url = jdbc:postgresql://portfolio-e-commerce-db-5833.7tc.aws-eu-central-1.cockroachlabs.cloud:26257/simple-library-management-system?sslmode=require&sslrootcert=/home/vmelnikovux/.postgresql/root.crt&connectTimeout=60&socketTimeout=60&loginTimeout=60&tcpKeepAlive=true

spring.datasource.username=vladyslavmelnikov
spring.datasource.password=rr-YH2cylvbfoQDixh_vAA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.propertiesoperties.hibernate.default_batch_fetch_size=50

server.servlet.context-path=/api

# Local HTTP: SameSite=None requires Secure; keep false unless you use HTTPS locally.
app.security.cross-site-cookies=false

spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#spring.jpa.properties.hibernate.format_sql=true
